### ISSUE TITLE
Allow options to be passed

### ISSUE THREAD

**Issue by maggie0002** [ueberdosis/pandoc#15]
Great wrapper, supper helpful, thanks. 

Some food for thought, it would be helpful to be able to pass the many Pandoc options along on execution (https://pandoc.org/MANUAL.html). 

For example, --standalone, --columns, --toc-depth, the list goes on:

->options('standalone, columns=2, toc-depth=3')

**Comment by hanspagel** [comment]
I think I’d go with `->standalone()`, `->columnts(2)`, `->tocDepth(3)`. If you'd like to send a PR, I’m happy to look through!

**Comment by cheryllium** [comment]
Those would be great! How would you feel about also adding a generic `->argument($key, $value)` (or `->option($key, $value)`) method? For instance, `->option('standalone')`, `->option('columns', 2)`. That way, there would still be a way to specify the argument even if this library doesn't have a method implemented for that specific argument yet.

**Comment by hanspagel** [comment]
Sounds good too!

**Comment by cheryllium** [comment]
Hi again @hanspagel - I can take a shot at this if you'd like to assign me the issue :)
