### ISSUE TITLE
"standalone" should not be forced

### ISSUE THREAD

**Issue by jcatrysse** [ueberdosis/pandoc#31]
On line 200 of `pandoc/src/Pandoc.php` the `standalone `parameter has been forced, while I think this should not be the case.

This is problematic when converting strings to HTML because it returns a complete HTML file with headers and footers. The "standalone" parameter can already be used by `$this->option('standalone')`.

**Comment by timbrisc** [comment]
+1

**Comment by compilekaiten** [comment]
Is there a way to remove standalone?

Need this library for a project, but I don't need a full HTML document returned.

**Comment by mejo-** [comment]
I agree, and I also ran into problems with `standalone` being enforced. Passing paths to custom LUA writers to `--to` doesn't work together with `--standalone`. So far, my workaround is to use `Pandoc->execute()` instead of `Pandoc->run()`, but that feels like an unnecessary hack.

**Comment by compilekaiten** [comment]
@patrickbaber Could this be merged? Or is there any response from the team?
